version: '3.8'


include:
  - path:
    - ../DOCKERCOMPONENT/docker-compose-net.yml
    - ../DOCKERCOMPONENT/docker-compose-volume.yml
    env_file: .env

services:
  mysql-apione:
    container_name: mysql-apione
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=bookstack
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=secret
    volumes:
      - ./database:/var/lib/mysql
    networks:
      - db-networks
      - laravel-apione

  apione:
    build:
      dockerfile:  ${PROJECTDIR}/apiOne/Dockerfile
    container_name: apione
    volumes:
      - ${PROJECTDIR}/apiOne/apione:/var/www/html
      - ${PROJECTDIR}/apiOne/apache-config.conf:/etc/apache2/sites-available/000-default.conf
      - ${PROJECTDIR}/apiOne/ports.conf:/etc/apache2/ports.conf
    ports:
      - "8080:82"
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    networks:
      - db-networks
      - laravel-apitwo
    depends_on:
      - mysql-apione

  phpmyadminapione:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST:  research_DB
      PMA_PORT: 3306
    depends_on:
      - mysql-apione
    networks:
      - db-networks
      - laravel-apitwo